RoJ = {
    "ID": "6969",
    "Book": "Rómeo a Jůlie",
    "Author": "Jiří Pölzer",
    "Hl.Postavy":"Wisman a Geošek",
    "Dělka v h": "1"
}
Ham = {
    "ID": "8888",
    "Book": "Hamlet",
    "Author": "DAvýýýd",
    "Hl.Postavy":"William Shakespeare",
    "Dělka v h": "4"
}
Nig = {
    "ID": "201588619", //šifra (nige..)
    "Book": "Rom",
    "Author": "Nick/Her",
    "Hl.Postavy":"Wisman a Geošek",
    "Dělka v h": "1h"
}
Knih[RoJ,Ham,Nig]
